version: '3.8'  #Upgraded to 3.8

services:
  selenium-hub:
    image: selenium/hub #Example of explicit version
    ports:
      - "4442-4444:4442-4444"
    networks:
      - grid

  node-chrome:
    image: selenium/node-chrome #Example of explicit version
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    volumes:
      - "${PWD}/resources/:/home/selenium/resources/"
    networks:
      - grid
 

  node-firefox:
    image: selenium/node-firefox #Example of explicit version
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    volumes:
      - "${PWD}/resources/:/home/selenium/resources/"
    networks:
      - grid
   

networks:
  grid:
    driver: bridge
